// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yejvehkqfbvbbpjnpwgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllanZlaGtxZmJ2YmJwam5wd2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTY2MzYsImV4cCI6MjA2NzEzMjYzNn0.Sua2yEYjf8s2nyAqB9bsBzr5O14LGXPwliXm3vf9oes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});